#!/usr/bin/env bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT

set -e

USAGE="""
Usage:
  create-environment -e {pre-prod|config-dev} [-v]
  create-environment -h

Options:
  -e {pre-prod}         Used to create environment for the pre-prod example.
  -e {pre-prod}         Used to create environment for the config development environment.
  -h                    Display the help.
  -v                    Verbose output.
"""

source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/common_functions.sh"
OPTIONS_FOR="createEnvironment"
parse_arguments "$@"

# Load common functions
source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/common_functions.sh"
source "${ANALYZE_CONTAINERS_ROOT_DIR}/version.conf"

# Load common variables
check_environment_is_valid
if [[ "${ENVIRONMENT}" == "pre-prod" ]]; then
  source "${ANALYZE_CONTAINERS_ROOT_DIR}/examples/pre-prod/utils/simulated_external_variables.sh"
elif [[ "${ENVIRONMENT}" == "config-dev" ]]; then
  source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/simulated_external_variables.sh"
fi
source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/common_variables.sh"
source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/internal_helper_variables.sh"

###############################################################################
# Variables                                                                   #
###############################################################################

LIBERTY_CONFIG_APP="${IMAGES_DIR}/liberty_ubi_base/application"
SOLR_IMAGES_DIR="${IMAGES_DIR}/solr_redhat"
ETL_CLIENT_LIB_DIR="${LOCAL_ETL_TOOLKIT_DIR}/lib"
TOOLKIT_APPLICATION_DIR="${LOCAL_TOOLKIT_DIR}/application"
ETL_TOOLKIT_DIR="${LOCAL_TOOLKIT_DIR}/examples/etl/toolkit"
TOOLKIT_SCRIPTS_DIR="${LOCAL_TOOLKIT_DIR}/i2-tools/scripts"
TOOLKIT_EXAMPLE_CONNECTOR_DIR="${LOCAL_TOOLKIT_DIR}/examples/connectors/example-connector"
FIXPACK_DIR="${PRE_REQS_DIR}/fixpack"

###############################################################################
# Function definitions                                                        #
###############################################################################

function extract_toolkit() {
  local toolkit_minimal_version
  print "Setting up i2 Analyze Minimal Toolkit"

  delete_folder_if_exists "${LOCAL_I2ANALYZE_DIR}"
  mkdir -p "${LOCAL_I2ANALYZE_DIR}"

  tar -zxf "${PRE_REQS_DIR}/i2analyzeMinimal.tar.gz" -C "${LOCAL_I2ANALYZE_DIR}"
  toolkit_minimal_version=$(cat "${LOCAL_I2ANALYZE_DIR}/toolkit/scripts/version.txt")
  if [[ "${toolkit_minimal_version%.*}" != "${SUPPORTED_I2ANALYZE_VERSION}" ]]; then
    print_error_and_exit "i2 Analyze Minimal Toolkit version ${toolkit_minimal_version%%-*} is not compatible with analyze-containers version ${VERSION}"
  fi
}

function extract_fixpack_if_necessary() {
  local fixpack_version

  if [[ -f "${PRE_REQS_DIR}/i2analyzeFixPack.tar.gz" ]]; then
    delete_folder_if_exists_and_create "${FIXPACK_DIR}"
    tar -zxf "${PRE_REQS_DIR}/i2analyzeFixPack.tar.gz" -C "${FIXPACK_DIR}"
    fixpack_version=$(cat "${FIXPACK_DIR}"/toolkit/version/*.txt)
    if [[ "${fixpack_version%.*}" != "${SUPPORTED_I2ANALYZE_VERSION}" ]]; then
      print_error_and_exit "Fix Pack version ${fixpack_version} is not compatible with i2 Analyze Toolkit Minimal version ${SUPPORTED_I2ANALYZE_VERSION}"
    fi
    print "Applying i2 Analyze Fix Pack ${fixpack_version}"
    if [[ -d "${FIXPACK_DIR}/toolkit/application/dependencies/solr-extension" && "$(ls -A "${FIXPACK_DIR}/toolkit/application/dependencies/solr-extension")" ]]; then
      cp -r "${FIXPACK_DIR}/toolkit/application/dependencies/solr-extension/." "${TOOLKIT_APPLICATION_DIR}/dependencies/solr-extension"
    fi
    if [[ -d "${FIXPACK_DIR}/toolkit/application/shared" && "$(ls -A "${FIXPACK_DIR}/toolkit/application/shared")" ]]; then
      cp -r "${FIXPACK_DIR}/toolkit/application/shared/." "${TOOLKIT_APPLICATION_DIR}/shared"
    fi
    if [[ -d "${FIXPACK_DIR}/toolkit/application/targets/opal-services-is-daod" && "$(ls -A "${FIXPACK_DIR}/toolkit/application/targets/opal-services-is-daod")" ]]; then
      cp -r "${FIXPACK_DIR}/toolkit/application/targets/opal-services-is-daod/." "${TOOLKIT_APPLICATION_DIR}/targets/opal-services"
    fi
    if [[ -d "${FIXPACK_DIR}/toolkit/scripts/xsd" && "$(ls -A "${FIXPACK_DIR}/toolkit/scripts/xsd")" ]]; then
      cp -r "${FIXPACK_DIR}/toolkit/scripts/xsd/." "${LOCAL_TOOLKIT_DIR}/scripts/xsd"
    fi
    if [[ -d "${FIXPACK_DIR}/toolkit/scripts-bin/buildSrc" && "$(ls -A "${FIXPACK_DIR}/toolkit/scripts-bin/buildSrc")" ]]; then
      cp -r "${FIXPACK_DIR}/toolkit/scripts-bin/buildSrc/." "${LOCAL_TOOLKIT_DIR}/i2-tools/jars"
    fi
    find "${FIXPACK_DIR}/toolkit/version/" -type f -name "*.txt" -print0 | xargs -I{} -0 cp {} "${LOCAL_TOOLKIT_DIR}/scripts/version.txt"
  fi
  delete_folder_if_exists "${FIXPACK_DIR}"
}

function populate_images_folders_with_environment_tool() {
  print "Adding environment variable resolution support"
  cp -p "${TOOLKIT_SCRIPTS_DIR}/utils/environment.sh" "${IMAGES_DIR}/sql_client/db-scripts"
  cp -p "${TOOLKIT_SCRIPTS_DIR}/utils/environment.sh" "${IMAGES_DIR}/db2_client/db-scripts"
  cp -p "${TOOLKIT_SCRIPTS_DIR}/utils/environment.sh" "${IMAGES_DIR}/db2_server"
  cp -p "${TOOLKIT_SCRIPTS_DIR}/utils/environment.sh" "${IMAGES_DIR}/postgres_client/db-scripts"
  cp -p "${TOOLKIT_SCRIPTS_DIR}/utils/environment.sh" "${IMAGES_DIR}/example_connector"
  cp -p "${TOOLKIT_SCRIPTS_DIR}/utils/environment.sh" "${IMAGES_DIR}/etl_client"
  cp -p "${TOOLKIT_SCRIPTS_DIR}/utils/environment.sh" "${IMAGES_DIR}/i2a_tools"
  cp -p "${TOOLKIT_SCRIPTS_DIR}/utils/environment.sh" "${IMAGES_DIR}/ha_proxy"
  cp -p "${TOOLKIT_SCRIPTS_DIR}/utils/environment.sh" "${TEMPLATES_DIR}/node-connector-image"
  cp -p "${TOOLKIT_SCRIPTS_DIR}/utils/environment.sh" "${TEMPLATES_DIR}/springboot-connector-image"
}

function create_solr_image_resources() {
  print "Creating Solr configuration folders"

  delete_folder_if_exists "${SOLR_IMAGES_DIR}/jars"
  mkdir -p "${SOLR_IMAGES_DIR}/jars/solr-data"

  cp -pr "${TOOLKIT_APPLICATION_DIR}/dependencies/solr-core-extension/." "${SOLR_IMAGES_DIR}/jars/"
  cp -pr "${TOOLKIT_APPLICATION_DIR}/dependencies/solr-jetty-wrapper/." "${SOLR_IMAGES_DIR}/jars/"
  cp -pr "${LOCAL_TOOLKIT_DIR}/application/dependencies/solr-extension/." "${SOLR_IMAGES_DIR}/jars/solr-data/"
}

function create_etl_toolkit_image_resources() {
  print "Setting up ETL Toolkit"

  delete_folder_if_exists "${LOCAL_ETL_TOOLKIT_DIR}"
  mkdir -p "${LOCAL_ETL_TOOLKIT_DIR}"
  mkdir -p "${ETL_CLIENT_LIB_DIR}"

  cp -pr "${ETL_TOOLKIT_DIR}/." "${LOCAL_ETL_TOOLKIT_DIR}"
  cp -pr "${PRE_REQS_DIR}/jdbc-drivers/." "${ETL_CLIENT_LIB_DIR}"
  cp -pr "${LOCAL_TOOLKIT_DIR}/i2-tools/jars/." "${ETL_CLIENT_LIB_DIR}"
}

function populate_image_folder_with_tools_resources() {
  local IMAGE_FOLDER="$1"
  print "Setting up ${IMAGE_FOLDER} image"

  delete_folder_if_exists "${IMAGES_DIR}/${IMAGE_FOLDER}/tools"
  mkdir -p "${IMAGES_DIR}/${IMAGE_FOLDER}/tools"

  cp -pr "${LOCAL_TOOLKIT_DIR}/i2-tools" "${IMAGES_DIR}/${IMAGE_FOLDER}/tools"
  cp -pr "${LOCAL_TOOLKIT_DIR}/scripts" "${IMAGES_DIR}/${IMAGE_FOLDER}/tools"
}

function create_database_scripts_and_generated_folder() {
  print "Creating ${LOCAL_DATABASE_SCRIPTS_DIR}/generated folder"
  delete_folder_if_exists "${LOCAL_DATABASE_SCRIPTS_DIR}"
  mkdir -p "${LOCAL_DATABASE_SCRIPTS_DIR}/generated/dynamic"
}

function create_liberty_static_application() {
  print "Creating Liberty static application"
  delete_folder_if_exists "${LIBERTY_CONFIG_APP}"
  mkdir -p "${LIBERTY_CONFIG_APP}"

  "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/scripts/create-liberty-static-application" "${ENVIRONMENT}" "${LIBERTY_CONFIG_APP}"

  # Copy jdbc-drivers and verify they exist in the liberty image folder
  cp -pr "${PRE_REQS_DIR}/jdbc-drivers/." "${LIBERTY_CONFIG_APP}/third-party-dependencies/resources/jdbc/"
  if [ "$(ls -A "${LIBERTY_CONFIG_APP}/third-party-dependencies/resources/jdbc/mssql-jdbc-"*".jre11.jar")" ]; then
    print_info "${LIBERTY_CONFIG_APP}/third-party-dependencies/resources/jdbc has the mssql jdbc drivers"
  elif [ "$(ls -A "${LIBERTY_CONFIG_APP}/third-party-dependencies/resources/jdbc/postgresql-"*".jar")" ]; then
    print_info "${LIBERTY_CONFIG_APP}/third-party-dependencies/resources/jdbc has the postgres jdbc drivers"
  else
    print_error_and_exit "${PRE_REQS_DIR}/jdbc-drivers does NOT have the correct mssql or postgres jdbc drivers, expecting: mssql-jdbc-*.jre11.jar or postgresql-*.jar"
  fi
}

function create_example_connector_application() {
  print "Building example connector image"
  delete_folder_if_exists_and_create "${LOCAL_EXAMPLE_CONNECTOR_APP_DIR}"

  cp -pr "${TOOLKIT_EXAMPLE_CONNECTOR_DIR}/"* "${LOCAL_EXAMPLE_CONNECTOR_APP_DIR}"
}

function populate_connector_images_folder() {
  local i2connect_server_version_file="${CONNECTOR_IMAGES_DIR}/i2connect-server-version.json"
  print "Populate connector-images folder with defaults"
  create_folder "${PREVIOUS_CONNECTOR_IMAGES_DIR}"

  if [[ ! -f "${i2connect_server_version_file}" ]]; then
    jq -n "{\"version\": \"latest\"}" >"${i2connect_server_version_file}"
  fi
}

function generate_default_files() {
  if [[ "${ENVIRONMENT}" == "config-dev" ]]; then
    if [[ ! -f "${ANALYZE_CONTAINERS_ROOT_DIR}/path-configuration.json" ]]; then
      jq -n '{}' >"${ANALYZE_CONTAINERS_ROOT_DIR}/path-configuration.json"
    fi
  fi
}

function main() {
  ###############################################################################
  # Setting up i2 Analyze toolkit                                               #
  ###############################################################################
  extract_toolkit
  extract_fixpack_if_necessary

  ###############################################################################
  # Adding environment variable resolution support                              #
  ###############################################################################
  populate_images_folders_with_environment_tool

  ###############################################################################
  # Creating Solr configuration folders                                         #
  ###############################################################################
  create_solr_image_resources

  ###############################################################################
  # Setting up ETL Toolkit                                                      #
  ###############################################################################
  create_etl_toolkit_image_resources

  ###############################################################################
  # Setting up i2 tools image                                                   #
  ###############################################################################
  populate_image_folder_with_tools_resources "i2a_tools"
  populate_image_folder_with_tools_resources "sql_client"
  populate_image_folder_with_tools_resources "postgres_client"
  if [[ "${DEV_DB2_BUILD}" == "true" ]]; then
    populate_image_folder_with_tools_resources "db2_client"
  fi

  # Copy changelog.json to correct folder
  cp "${LOCAL_TOOLKIT_DIR}/scripts/changelog.json" "${IMAGES_DIR}/i2a_tools"

  ###############################################################################
  # Creating Example connector application                                      #
  ###############################################################################
  create_example_connector_application

  ###############################################################################
  # Creating Database scripts folder                                            #
  ###############################################################################
  create_database_scripts_and_generated_folder

  ###############################################################################
  # Creating Liberty static application                                         #
  ###############################################################################
  create_liberty_static_application

  ###############################################################################
  # Populate Connector Images folder with defaults                              #
  ###############################################################################
  populate_connector_images_folder

  ###############################################################################
  # Create License Configuration                                                #
  ###############################################################################
  create_license_configuration

  ###############################################################################
  # Generate Default Files                                                      #
  ###############################################################################
  generate_default_files

  print_success "Environment has been successfully prepared"
}

main "$@"
