#!/usr/bin/env bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022)
#
# SPDX short identifier: MIT

set -e

USAGE="""
Usage:
  create-change-set -e {pre-prod|config-dev} -t {upgrade|update} [-c <config_name>] [-n <change_set_number>]
  create-change-set -e pre-prod -t upgrade [-n <change_set_number>]
  create-change-set -e config-dev -t {upgrade|update} [-n <change_set_number>]
  create-change-set -h

Options:
  -e {pre-prod}             Used to generate images for the pre-prod example.
  -e {config-dev}           Used to generate images for the configuration development.
  -c <config_name>          Name of the config to use.
  -t <type>                 The type of the config-set.
  -n <change_set_number>    The number of config-set to be created.
  -v                        Verbose output.
  -h                        Display the help.
"""

source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/common_functions.sh"
OPTIONS_FOR="createChangeSet"
parse_arguments "$@"

function source_common_variables_and_scripts() {
  # Load common functions
  source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/server_functions.sh"
  source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/client_functions.sh"

  # Load common variables
  if [[ "${ENVIRONMENT}" == "pre-prod" ]]; then
    source "${ANALYZE_CONTAINERS_ROOT_DIR}/examples/pre-prod/utils/simulated_external_variables.sh"
  else
    source "${ANALYZE_CONTAINERS_ROOT_DIR}/configs/${CONFIG_NAME}/utils/variables.conf"
    source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/simulated_external_variables.sh"
  fi
  source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/common_variables.sh"
  source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/internal_helper_variables.sh"
}

function next_change_set_number() {
  local next_change_set_number
  # shellcheck disable=SC2012
  if [[ -d ${CHANGE_SETS_DIR} && $(ls -A "${CHANGE_SETS_DIR}") ]]; then
    next_change_set_number=$(ls "${CHANGE_SETS_DIR}" | sort -V | tail -n 1 | sed 's/-.*//')
    ((next_change_set_number++))
    echo "${next_change_set_number}"
  else
    echo 1
  fi
}

function validate_arguments() {
  if [[ -z "${ENVIRONMENT}" ]]; then
    print_usage 1
  fi
  [[ "${ENVIRONMENT}" == "pre-prod" || "${ENVIRONMENT}" == "config-dev" ]] || print_usage 1

  if [[ "${ENVIRONMENT}" == "pre-prod" ]]; then
    [[ "${TYPE}" == "upgrade" || "${TYPE}" == "update" ]] || print_usage 1
  else
    if [[ -z "${CONFIG_NAME}" ]]; then
      print_usage 1
    fi
    [[ "${TYPE}" == "upgrade" || "${TYPE}" == "update" ]] || print_usage 1
  fi
}

function set_environment_variables() {
  local dir_name="${1:-${TYPE}}"

  if [[ "${ENVIRONMENT}" == "pre-prod" ]]; then
    CHANGE_SETS_DIR="${LOCAL_CHANGE_SETS_DIR}"
  else
    CHANGE_SETS_DIR="${LOCAL_USER_CHANGE_SETS_DIR}"
  fi

  if [[ -z "${CHANGE_SET_NUMBER}" ]]; then
    CHANGE_SET_NUMBER=$(next_change_set_number)
  fi

  CHANGE_SET_DIR="${CHANGE_SETS_DIR}/${CHANGE_SET_NUMBER}-${dir_name}-$(date "+%Y.%m.%d-%H.%M")"

  CONFIG_CHANGE_SET_DIR="${CHANGE_SET_DIR}/configuration"
  DB_CHANGE_SET_DIR="${CHANGE_SET_DIR}/database-scripts/generated"

  if [[ "${ENVIRONMENT}" == "pre-prod" ]]; then
    CONFIG_DIR="${LOCAL_CONFIG_DIR}"
  else
    CONFIG_DIR="${LOCAL_USER_CONFIG_DIR}"
  fi

  # Only .properties files are supported at the moment
  FILES_TO_UPGRADE=(
    "InfoStoreNamesDb2.properties"
    "InfoStoreNamesSQLServer.properties"
    "InfoStoreNamesPostgres.properties"
    "DiscoSolrConfiguration.properties"
  )

  ALL_PATTERNS_CONFIG_DIR="${LOCAL_TOOLKIT_DIR}/examples/configurations/all-patterns/configuration"
}

function set_supported_versions() {
  if [[ "${ENVIRONMENT}" == "pre-prod" ]]; then
    source "${LOCAL_CONFIG_DIR}/version.conf"
  else
    source "${ANALYZE_CONTAINERS_ROOT_DIR}/configs/${CONFIG_NAME}/version.conf"
  fi
  CONFIG_SUPPORTED_I2ANALYZE_VERSION="${SUPPORTED_I2ANALYZE_VERSION}"
  source "${ANALYZE_CONTAINERS_ROOT_DIR}/version.conf"
  CURRENT_SUPPORTED_I2ANALYZE_VERSION="${SUPPORTED_I2ANALYZE_VERSION}"
}

function create_change_set_version_file() {
  echo -e "FROM_SUPPORTED_I2ANALYZE_VERSION=${CONFIG_SUPPORTED_I2ANALYZE_VERSION}\nTO_SUPPORTED_I2ANALYZE_VERSION=${CURRENT_SUPPORTED_I2ANALYZE_VERSION}" >"${CHANGE_SET_DIR}/version.conf"
}

function create_upgrade_change_set() {
  print "Creating Change-Set: ${CHANGE_SET_DIR}"
  set_supported_versions

  create_folder "${CHANGE_SET_DIR}"

  if [[ "${DEPLOYMENT_PATTERN}" == *"store"* ]]; then
    local previous_db_container_name
    if [[ "${ENVIRONMENT}" == "pre-prod" ]]; then
      previous_db_container_name="sqlserver"
    else
      if [[ "${CONFIG_SUPPORTED_I2ANALYZE_VERSION}" < "4.4.0" ]]; then
        previous_db_container_name="sqlserver.${CONFIG_NAME}_${CONFIG_SUPPORTED_I2ANALYZE_VERSION%.*}"
      else
        previous_db_container_name="sqlserver.${CONFIG_NAME}_${CONFIG_SUPPORTED_I2ANALYZE_VERSION}"
      fi
    fi
    # Restart Docker containers
    print "Restarting container: ${previous_db_container_name}"
    docker start "${previous_db_container_name}"
    wait_for_sql_server_to_be_live
    create_database_upgrade_change_set
  fi
  create_configuration_upgrade_change_set

  if [[ ! $(ls -A "${CHANGE_SET_DIR}") ]]; then
    print "No upgrade changes detected"
    rm -r "${CHANGE_SET_DIR}"
  else
    create_change_set_version_file
  fi
}

function create_update_change_set() {
  print "Creating Change-Set: ${CHANGE_SET_DIR}"
  create_update_schema_change_set
}

function create_update_schema_change_set() {
  local errors_message="Validation errors detected, please review the above message(s)"
  local db_update_dir="${DB_CHANGE_SET_DIR}/update"

  if [[ "${DEPLOYMENT_PATTERN}" == *"store"* ]]; then
    print "Validating the schema"
    if ! run_i2_analyze_tool "/opt/i2-tools/scripts/validateSchemaAndSecuritySchema.sh" >'/tmp/result_validate_security_schema'; then
      echo "[INFO] Response from i2 Analyze Tool: $(cat '/tmp/result_validate_security_schema')"
      # check i2 Analyze Tool for output indicating a Schema change has occurred, if so then prompt user for destructive
      # rebuild of ISTORE database.
      #
      # Note the error message from i2 Analyze is currently not great and incorrectly indicates that the 'Schema file
      # is not valid', what it really means is its not valid for the current deployment and thus must be re-deployed via
      # a destructive change to the ISTORE database.
      if grep -q 'ERROR: The new Schema file is not valid, see the summary for more details.' '/tmp/result_validate_security_schema'; then
        echo "[WARN] Destructive Schema change(s) detected"
        set_environment_variables "reset"

        run_i2_analyze_tool "/opt/i2-tools/scripts/generateInfoStoreToolScripts.sh"
        run_i2_analyze_tool "/opt/i2-tools/scripts/generateStaticInfoStoreCreationScripts.sh"
        run_i2_analyze_tool "/opt/i2-tools/scripts/generateDynamicInfoStoreCreationScripts.sh"

        create_folder "${DB_CHANGE_SET_DIR}/static"
        create_folder "${DB_CHANGE_SET_DIR}/dynamic"

        cp -Rp "${LOCAL_GENERATED_DIR}/static/." "${DB_CHANGE_SET_DIR}/static"
        cp -Rp "${LOCAL_GENERATED_DIR}/dynamic/." "${DB_CHANGE_SET_DIR}/dynamic"

        create_folder "${CONFIG_CHANGE_SET_DIR}"
        cp "${CONFIG_DIR}/schema.xml" "${CONFIG_CHANGE_SET_DIR}"
      else
        print_error_and_exit "[INFO] Response from i2 Analyze Tool: $(cat '/tmp/result_validate_security_schema')"
      fi
    else
      delete_folder_if_exists "${LOCAL_GENERATED_DIR}/update"

      print "Generating update schema scripts"
      run_i2_analyze_tool "/opt/i2-tools/scripts/generateUpdateSchemaScripts.sh"
      if [ -d "${LOCAL_GENERATED_DIR}/update" ]; then
        if [ "$(ls -A "${LOCAL_GENERATED_DIR}/update")" ]; then
          create_folder "${db_update_dir}"
          cp "${LOCAL_GENERATED_DIR}/update/"* "${db_update_dir}"
          for file in "${db_update_dir}/"*; do
            if [[ ! -s "${file}" ]]; then
              rm "${file}"
            fi
          done
          create_folder "${CONFIG_CHANGE_SET_DIR}"
          cp "${CONFIG_DIR}/schema.xml" "${CONFIG_CHANGE_SET_DIR}"
        else
          print_info "No files present in update schema scripts folder"
        fi
      else
        print_info "Update schema scripts folder doesn't exist"
      fi
    fi
  fi
}

function create_change_set() {
  if [[ "${TYPE}" == "upgrade" ]]; then
    create_upgrade_change_set
  elif [[ "${TYPE}" == "update" ]]; then
    create_update_change_set
  fi
}

function create_database_upgrade_change_set() {
  local db_upgrade_dir="${DB_CHANGE_SET_DIR}/upgrade"

  print "Generating Database Upgrade Change-Set"
  run_i2_analyze_tool "/opt/i2-tools/scripts/generateInfoStoreToolScripts.sh"
  run_i2_analyze_tool "/opt/i2-tools/scripts/generateStaticInfoStoreCreationScripts.sh"
  run_i2_analyze_tool "/opt/i2-tools/scripts/generateDynamicInfoStoreCreationScripts.sh"

  find "${LOCAL_GENERATED_DIR}/static/" -maxdepth 1 -type f -exec cp {} "${LOCAL_GENERATED_DIR}" \;
  mkdir -p "${LOCAL_GENERATED_DIR}/upgrade"
  cp "${LOCAL_GENERATED_DIR}/static/2020-create-deletion-by-rule-routines.sql" "${LOCAL_GENERATED_DIR}/upgrade"

  run_i2_analyze_tool "/opt/i2-tools/scripts/generateDatabaseUpgradeScripts.sh"

  if [[ -d "${LOCAL_GENERATED_DIR}/upgrade" && $(ls -A "${LOCAL_GENERATED_DIR}/upgrade") ]]; then
    create_folder "${db_upgrade_dir}"
    cp "${LOCAL_GENERATED_DIR}/upgrade/"* "${db_upgrade_dir}"
    for file in "${db_upgrade_dir}/"*; do
      [[ -s "${file}" ]] || rm "${file}"
    done
  else
    echo "Database is already at the latest version"
  fi
}

function check_collection_exists() {
  local collection="$1"
  local json
  json=$(run_solr_client_command bash -c "curl -u \"\${SOLR_ADMIN_DIGEST_USERNAME}:\${SOLR_ADMIN_DIGEST_PASSWORD}\" --cacert ${CONTAINER_CERTS_DIR}/CA.cer \"${SOLR1_BASE_URL}/solr/${collection}/admin/ping\"")
  if jq -e . >/dev/null 2>&1 <<<"$json"; then
    status=$(echo "$json" | jq -r ".status")
    [[ "${status}" == "OK" ]] && echo "true" || echo "false"
  else
    echo "false"
  fi
}

function create_configuration_upgrade_change_set() {
  print "Generating Configuration Upgrade Change-Set"

  declare -A properties
  local files_upgraded=()
  local filepath
  # Liberty
  if [[ "${ENVIRONMENT}" == "pre-prod" ]]; then
    delete_folder_if_exists_and_create "${PRE_PROD_DIR}/.configuration_old"
    cp -Rp "${CONFIG_DIR}/." "${PRE_PROD_DIR}/.configuration_old"

    "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/scripts/create-configuration" -e "${ENVIRONMENT}"
    delete_folder_if_exists_and_create "${PRE_PROD_DIR}/.configuration_new"
    cp -Rp "${CONFIG_DIR}/." "${PRE_PROD_DIR}/.configuration_new"
    delete_folder_if_exists_and_create "${CONFIG_DIR}"
    cp -Rp "${PRE_PROD_DIR}/.configuration_old/." "${CONFIG_DIR}"

    for file in "${FILES_TO_UPGRADE[@]}"; do
      filepath=$(find "${CONFIG_DIR}" -type f -name "${file}" -print0 | xargs -0)

      checksumPrevious=$(shasum "${PRE_PROD_DIR}/.configuration_new/${filepath//${CONFIG_DIR}/}" | cut -d ' ' -f 1)
      checksumCurrent=$(shasum "${filepath}" | cut -d ' ' -f 1)
      # if checksums different then add to changeset
      if [[ "$checksumPrevious" != "$checksumCurrent" ]]; then
        print_info "Adding changed file to changeset: ${file}"
        mkdir -p "$(dirname "${CONFIG_CHANGE_SET_DIR}/${filepath//${CONFIG_DIR}/}")"
        cp -Rp "${PRE_PROD_DIR}/.configuration_new/${filepath//${CONFIG_DIR}/}" "${CONFIG_CHANGE_SET_DIR}/${filepath//${CONFIG_DIR}/}"
        cp -Rp "${PRE_PROD_DIR}/.configuration_new/${filepath//${CONFIG_DIR}/}" "${filepath}"
      fi
    done

    rm -R "${PRE_PROD_DIR}/.configuration_old" "${PRE_PROD_DIR}/.configuration_new"
  else
    for file in "${FILES_TO_UPGRADE[@]}"; do
      properties=()

      while IFS= read -r line; do
        [[ "${line}" =~ ^#.* ]] && continue
        [[ -z "${line}" ]] && continue
        properties["${line%%=*}"]="${line#*=}"
      done <"${LOCAL_CONFIG_DEV_DIR}/configuration/${file}"

      # Add empty new line if none
      if [[ -n "$(tail -c1 "${CONFIG_DIR}/${file}")" ]]; then
        echo >>"${CONFIG_DIR}/${file}"
      fi
      for prop in "${!properties[@]}"; do
        if grep -q -E -o -m 1 "${prop}" <"${CONFIG_DIR}/${file}"; then
          continue
        fi
        echo "${prop}=${properties["${prop}"]}" >>"${CONFIG_DIR}/${file}"

        if ! is_string_in_array "${CONFIG_DIR}/${file}" files_upgraded; then
          files_upgraded+=("${CONFIG_DIR}/${file}")
        fi
      done
    done
    for file in "${files_upgraded[@]}"; do
      filepath="${file//"${CONFIG_DIR}/"/}"
      print_info "Adding changed file to changeset: ${filepath}"
      mkdir -p "$(dirname "${CONFIG_CHANGE_SET_DIR}/${filepath}")"
      cp -Rp "${file}" "${CONFIG_CHANGE_SET_DIR}/${filepath}"
    done
  fi

  # Solr
  delete_folder_if_exists_and_create "${CONFIG_DIR}/solr/.generated_config"
  cp -Rp "${CONFIG_DIR}/solr/generated_config/." "${CONFIG_DIR}/solr/.generated_config"
  run_i2_analyze_tool "/opt/i2-tools/scripts/generateSolrSchemas.sh"
  if [[ "${ENVIRONMENT}" != "pre-prod" ]]; then
    # in pre-prod they are the same
    cp -Rp "${LOCAL_CONFIG_DIR}/solr/generated_config" "${CONFIG_DIR}/solr"
  fi

  for file in "${CONFIG_DIR}/solr/generated_config/"* "${CONFIG_DIR}/solr/generated_config/"**/*; do
    [[ ! -f "${file}" ]] && continue
    filepath="${file//"${CONFIG_DIR}/solr/generated_config/"/}"
    if [[ ! -f "${CONFIG_DIR}/solr/.generated_config/${filepath}" ]]; then
      print_info "Adding new file to changeset: ${filepath}"
      mkdir -p "$(dirname "${CONFIG_DIR}/solr/.generated_config/${filepath}")"
      cp -Rp "${file}" "${CONFIG_DIR}/solr/.generated_config/${filepath}"
      continue
    fi

    checksumPrevious=$(shasum "${CONFIG_DIR}/solr/.generated_config/${filepath}" | cut -d ' ' -f 1)
    checksumCurrent=$(shasum "${file}" | cut -d ' ' -f 1)
    # if checksums different then new config otherwise delete from changeset
    if [[ "$checksumPrevious" == "$checksumCurrent" ]]; then
      print_info "Deleting non-changed file from changeset: ${filepath}"
      rm "${CONFIG_DIR}/solr/.generated_config/${filepath}"
    else
      print_info "Adding changed file to changeset: ${filepath}"
      mkdir -p "$(dirname "${CONFIG_DIR}/solr/.generated_config/${filepath}")"
      cp -Rp "${file}" "${CONFIG_DIR}/solr/.generated_config/${filepath}"
    fi
  done

  if [[ $(find "${CONFIG_DIR}/solr/.generated_config" -type f -print0 | xargs -0) ]]; then
    create_folder "${CONFIG_CHANGE_SET_DIR}/solr/generated_config"
    cp -Rp "${CONFIG_DIR}/solr/.generated_config/." "${CONFIG_CHANGE_SET_DIR}/solr/generated_config"
    find "${CONFIG_DIR}/solr/.generated_config/" -empty -type d -delete
  else
    echo "Solr configuration is already at the latest version"
  fi
  rm -R "${CONFIG_DIR}/solr/.generated_config"
}

function main() {
  parse_arguments "$@"
  source_common_variables_and_scripts
  validate_arguments
  set_environment_variables
  create_change_set
}

main "$@"
