#!/usr/bin/env bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT

set -e

if [[ -z "${ANALYZE_CONTAINERS_ROOT_DIR}" ]]; then
  echo "ANALYZE_CONTAINERS_ROOT_DIR variable is not set"
  echo "This project should be run inside a VSCode Dev Container. For more information read, the Getting Started guide at https://i2group.github.io/analyze-containers/content/getting_started.html"
  exit 1
fi

# Load common functions
source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/common_functions.sh"

# Load common variables
source "${ANALYZE_CONTAINERS_ROOT_DIR}/examples/pre-prod/utils/simulated_external_variables.sh"
source "${ANALYZE_CONTAINERS_ROOT_DIR}/version.conf"

create_license_configuration

print "Running create-environment script"
"${ANALYZE_CONTAINERS_ROOT_DIR}/utils/scripts/create-environment" -e "${ENVIRONMENT}"

print "Running create-configuration"
"${ANALYZE_CONTAINERS_ROOT_DIR}/utils/scripts/create-configuration" -e "${ENVIRONMENT}"

set_dependencies_tag_if_necessary

print "Running build-images"
"${ANALYZE_CONTAINERS_ROOT_DIR}/utils/scripts/build-images" -e "${ENVIRONMENT}"

print "Running generate-secrets"
"${ANALYZE_CONTAINERS_ROOT_DIR}/utils/scripts/generate-secrets"

print_success "Pre-prod environment created"
