#!/usr/bin/env bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT

set -e

function run_task() {
  local task="$1"
  case "${task}" in
  "init")
    init
    ;;
  "create")
    create
    ;;
  "start")
    post_start
    ;;
  *)
    echo "Unknown task: ${task}" >&2
    exit 1
    ;;
  esac
}

function init() {
  docker pull i2group/i2eng-analyze-containers-dev:1.1
  mkdir -p "${HOME}/.m2" "${HOME}/.config/gh"
}

function install_analyze_containers_deps() {
  if [[ -d "${ANALYZE_CONTAINERS_ROOT_DIR}/pre-reqs/i2analyze/toolkit" ]]; then
    # Ensure to install the maven dependencies and images
    source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/common_functions.sh"
    source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/simulated_external_variables.sh"
    source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/common_variables.sh"
    pull_base_images
    setup_i2_analyze_maven_local
  fi
}

function create() {
  if [[ -z $(docker network ls -q --filter name="^eia$") ]]; then
    docker network create eia
  fi
  docker network connect eia "${HOSTNAME}"
  echo "VSCode dev container connected to docker network: eia"

  # This takes some time so slows down the first start of the devcontainer
  install_analyze_containers_deps
  echo "Done"
}

function post_start() {
  export ANALYZE_CONTAINERS_ROOT_DIR="${WORKSPACE}"
  export CONTINUE_ON_ERROR="true"

  "${ANALYZE_CONTAINERS_ROOT_DIR}/scripts/manage-environment" -t link
  install_analyze_containers_deps

  echo "Dev Container is ready"
}

run_task "$1"
