#!/usr/bin/env bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2024)
#
# SPDX short identifier: MIT

set -e

function run_task() {
  local task="$1"
  case "${task}" in
  "init")
    init
    ;;
  "create")
    create
    ;;
  "start")
    post_start
    ;;
  *)
    echo "Unknown task: ${task}" >&2
    exit 1
    ;;
  esac
}

function init() {
  docker pull i2group/i2eng-analyze-containers-dev:1.2
  # We want to create these folders inside the devcontainer so that they are owned by the user (not the same as HOST_HOME)
  mkdir -p "${HOME}/.m2" "${HOME}/.config/gh" "${HOME}/.circleci" "${HOME}/.jfrog"
  touch "${HOME}/.npmrc"
}

function create() {
  export ANALYZE_CONTAINERS_ROOT_DIR="${WORKSPACE}"
  export CONTINUE_ON_ERROR="true"
  if [[ -z $(docker network ls -q --filter name="^eia$") ]]; then
    docker network create eia
  fi
  docker network connect eia "${HOSTNAME}"
  echo "VSCode dev container connected to docker network: eia"
  echo "Done"
}

function post_start() {
  export ANALYZE_CONTAINERS_ROOT_DIR="${WORKSPACE}"
  export CONTINUE_ON_ERROR="true"
  if [[ -f "${ANALYZE_CONTAINERS_ROOT_DIR}/scripts/manage-environment" ]]; then
    "${ANALYZE_CONTAINERS_ROOT_DIR}/scripts/manage-environment" -t link
    echo "Dev Container is ready"
  else
    printf "\n\e[33mINFO: analyze-containers is not installed. To install analyze-containers, open a terminal in this VSCode window and run ./bootstrap\e[0m\n" >&2
  fi
  unset CONTINUE_ON_ERROR
}

run_task "$1"
