#!/usr/bin/env bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022)
#
# SPDX short identifier: MIT

echo "BASH_VERSION: $BASH_VERSION"
set -e

if [[ -z "${ANALYZE_CONTAINERS_ROOT_DIR}" ]]; then
  echo "ANALYZE_CONTAINERS_ROOT_DIR variable is not set"
  echo "This project should be run inside a VSCode Dev Container. For more information read, the Getting Started guide at https://i2group.github.io/analyze-containers/content/getting_started.html"
  exit 1
fi

USAGE="""
Usage:
  create-dev-environment [-v] [-y]
  create-dev-environment -h

Options:
  -v    Verbose output.
  -y    Answer 'yes' to all prompts.
  -h    Display the help.
"""

# Load common functions
source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/common_functions.sh"

# Parse arguments
OPTIONS_FOR="createDevEnv"
parse_arguments "$@"

# Load common variables
source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/simulated_external_variables.sh"
source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/common_variables.sh"
warn_root_dir_not_in_path
check_docker_is_running

extra_args=()
if [[ "${VERBOSE}" == "true" ]]; then
  extra_args+=("-v")
fi
if [[ "${YES_FLAG}" == "true" ]]; then
  extra_args+=("-y")
fi

print "Running create-environment script"
"${ANALYZE_CONTAINERS_ROOT_DIR}/utils/scripts/create-environment" -e "${ENVIRONMENT}" "${extra_args[@]}"

print "Running create-configuration"
"${ANALYZE_CONTAINERS_ROOT_DIR}/utils/scripts/create-configuration" -e "${ENVIRONMENT}" "${extra_args[@]}"

set_dependencies_tag_if_necessary
pullBaseImages

print "Running build-images"
"${ANALYZE_CONTAINERS_ROOT_DIR}/utils/scripts/build-images" "${extra_args[@]}"

print "Running generate-secrets"
"${ANALYZE_CONTAINERS_ROOT_DIR}/utils/scripts/generate-secrets" "${extra_args[@]}"

setupI2AnalyzeMavenLocal

print_success "Development environment created"
