#!/usr/bin/env bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022)
#
# SPDX short identifier: MIT

set -e

if [[ -z "${ANALYZE_CONTAINERS_ROOT_DIR}" ]]; then
  echo "ANALYZE_CONTAINERS_ROOT_DIR variable is not set" >&2
  echo "This project should be run inside a VSCode Dev Container. For more information read, the Getting Started guide at https://i2group.github.io/analyze-containers/content/getting_started.html" >&2
  exit 1
fi

USAGE="""
Usage:
  manage-toolkit-configuration -c <config_name> -n <toolkit_path_name> -t { create | prepare | import | export } [-v]
  manage-toolkit-configuration -h
Options:
  -c <config_name>             Name of the config to use.
  -n <toolkit_path_name>       The name of the path to the root of an i2 Analyze deployment toolkit as shown in the path-configuration.json file.
  -t {create}                  Creates a configuration in the i2 Analyze deployment toolkit that can be imported into the config development environment.
  -t {prepare}                 Prepares an existing i2 Analyze deployment toolkit configuration to be imported into the config development environment.
  -t {export}                  Export a config development environment configuration to an i2 Analyze deployment toolkit configuration.
  -t {import}                  Import an i2 Analyze deployment toolkit configuration to a config development environment configuration.
  -y                           Answer 'yes' to all prompts.
  -v                           Verbose output.
  -h                           Display the help.
"""

source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/common_functions.sh"

###############################################################################
# Function Definitions                                                        #
###############################################################################

function set_defaults() {
  # Local variables
  ON_PREM_CONFIG_DIR="${ON_PREM_TOOLKIT_DIR}/configuration"
  ENVIRONMENT_DIR="${ON_PREM_CONFIG_DIR}/environment"
  EXAMPLES_CONFIGS_DIR="${ON_PREM_TOOLKIT_DIR}/examples/configurations"
  FRAGMENTS_DIR="${ON_PREM_CONFIG_DIR}/fragments"
  COMMON_CLASSES_DIR="${FRAGMENTS_DIR}/common/WEB-INF/classes"
  OPAL_SERVICES_CLASSES_DIR="${FRAGMENTS_DIR}/opal-services/WEB-INF/classes"
  OPAL_SERVICES_PLUGINS_DIR="${FRAGMENTS_DIR}/opal-services/plugins"
  OPAL_SERVICES_IS_CLASSES_DIR="${FRAGMENTS_DIR}/opal-services-is/WEB-INF/classes"
  LIVE_DIR="${ON_PREM_CONFIG_DIR}/live"

  REQUIRED_COMMON_FIXED_FILE_NAMES=("${COMMON_CLASSES_DIR}/schema.xml"
    "${COMMON_CLASSES_DIR}/schema-charting-schemes.xml"
    "${COMMON_CLASSES_DIR}/security-schema.xml"
    "${COMMON_CLASSES_DIR}/mapping-configuration.json"
    "${OPAL_SERVICES_CLASSES_DIR}/command-access-control.xml"
    "${OPAL_SERVICES_CLASSES_DIR}/schema-vq-configuration.xml"
    "${OPAL_SERVICES_CLASSES_DIR}/schema-results-configuration.xml"
    "${OPAL_SERVICES_CLASSES_DIR}/schema-source-reference-schema.xml"
    "${LIVE_DIR}/fmr-match-rules.xml"
    "${LIVE_DIR}/geospatial-configuration.json"
    "${LIVE_DIR}/type-access-configuration.xml")

  REQUIRED_FRAGMENTS_FOR_ANALYZE_SETTINGS_FILE_NAMES=("${COMMON_CLASSES_DIR}/analyze-settings.properties"
    "${COMMON_CLASSES_DIR}/analyze-connect.properties"
    "${COMMON_CLASSES_DIR}/ApolloServerSettingsConfigurationSet.properties"
    "${COMMON_CLASSES_DIR}/ApolloServerSettingsMandatory.properties"
  )

  REQUIRED_FRAGMENTS_FOR_ISTORE_DEPLOYMENT_FILE_NAMES=("${OPAL_SERVICES_IS_CLASSES_DIR}/InfoStoreNamesDb2.properties"
    "${OPAL_SERVICES_IS_CLASSES_DIR}/InfoStoreNamesSQLServer.properties"
    "${OPAL_SERVICES_IS_CLASSES_DIR}/InfoStoreNamesPostgres.properties"
    "${LIVE_DIR}/highlight-queries-configuration.xml"
    "${ENVIRONMENT_DIR}/system-match-rules.xml"
  )

  REQUIRED_FRAGMENTS_FOR_I2C_DEPLOYMENT_FILE_NAMES=("${LIVE_DIR}/system-match-rules.xml")

  IGNORED_FIXED_FILE_NAMES=(
    "${COMMON_CLASSES_DIR}/log4j2.xml"
    "${OPAL_SERVICES_IS_CLASSES_DIR}/catalog.json"
  )

  declare -gA FIXED_PROPERTIES
  FIXED_PROPERTIES=(
    ["SchemaResource"]=schema.xml
    ["ChartingSchemesResource"]=schema-charting-schemes.xml
    ["DynamicSecuritySchemaResource"]=security-schema.xml
    ["ResultsConfigurationResource"]=schema-results-configuration.xml
    ["CommandAccessControlResource"]=command-access-control.xml
    ["SourceReferenceSchemaResource"]=schema-source-reference-schema.xml
    ["VisualQueryConfigurationResource"]=schema-vq-configuration.xml
    ["TypeMappingResource"]=mapping-configuration.json
  )

  REQUIRED_ON_PREM_TOOLKIT_DIRS=(
    "application"
    "bin"
    "examples"
    "scripts"
    "scripts-bin"
    "tools"
  )
}

function check_property_set_or_usage() {
  if [[ -z "$1" ]]; then
    print_usage 1
  fi
}

function validate_arguments() {
  [[ "${TASK}" == "import" || "${TASK}" == "export" || "${TASK}" == "create" || "${TASK}" == "prepare" ]] || print_usage 1

  check_property_set_or_usage "${CONFIG_NAME}"
  check_property_set_or_usage "${PATH_NAME}"
  ON_PREM_TOOLKIT_DIR="$(jq -r --arg name "${PATH_NAME}" '.externalDirectories[]? | select(.name==$name) .path' "${ANALYZE_CONTAINERS_ROOT_DIR}/path-configuration.json")"
  if [[ -z "${ON_PREM_TOOLKIT_DIR}" || "${ON_PREM_TOOLKIT_DIR}" == "null" ]]; then
    print_usage 1
  fi
  check_property_set_or_usage "${TASK}"
}

function source_common_variables_and_scripts() {
  # Load common functions
  source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/server_functions.sh"
  source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/client_functions.sh"

  # Load common variables
  source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/simulated_external_variables.sh"
  source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/common_variables.sh"
  source "${ANALYZE_CONTAINERS_ROOT_DIR}/utils/internal_helper_variables.sh"
  source "${ANALYZE_CONTAINERS_ROOT_DIR}/configs/${CONFIG_NAME}/utils/variables.conf"

  set_dependencies_tag_if_necessary
}

function check_file_exists_or_error() {
  local file="${1}"
  if [[ ! -f "${file}" ]]; then
    print_error_and_exit "The \"${file}\" file does not exist. Ensure that it is in the configuration directory and has the correct name."
  fi
}

function check_directory_exists_or_error() {
  local directory="${1}"
  if [[ ! -d "${directory}" ]]; then
    print_error_and_exit "The \"${directory}\" directory does not exist."
  fi
}

function check_is_valid_toolkit() {
  for directory in "${REQUIRED_ON_PREM_TOOLKIT_DIRS[@]}"; do
    if [[ ! -d "${ON_PREM_TOOLKIT_DIR}/${directory}" ]]; then
      print_error_and_exit "The specified toolkit is not valid, the \"${directory}\" directory does not exist."
    fi
  done
}

function run_top_level_checks() {
  check_directory_exists_or_error "${ANALYZE_CONTAINERS_ROOT_DIR}/configs/${CONFIG_NAME}/configuration"
  check_directory_exists_or_error "${ON_PREM_TOOLKIT_DIR}"
}

function run_low_level_checks() {
  check_is_valid_toolkit
  check_deployment_pattern_is_valid
}

function validate_and_list_connectors() {
  local connector_definitions_file="${GENERATED_LOCAL_CONFIG_DIR}/connectors-template.json"
  local topology_file="${ENVIRONMENT_DIR}/topology.xml"
  local config_connectors_ids
  local on_prem_connectors_ids
  local missing_connectors_ids
  local connector_id

  readarray -t config_connectors_ids < <(jq -r '.connectors // empty | .[].id' <"${connector_definitions_file}")
  readarray -t on_prem_connectors_ids < <(xmlstarlet sel -t -v "/ns1:topology/applications/application/wars/war/connector-ids/connector-id/@value" "${topology_file}")

  # Compute missing connectors in config-dev
  IFS=' ' read -r -a missing_connectors_ids <<<"$(subtract_array_from_array config_connectors_ids on_prem_connectors_ids)"

  if [[ -n "${missing_connectors_ids[*]}" ]]; then
    print "Connector ids missing in config-dev"
    printf "%s\n" "${missing_connectors_ids[@]}"
  fi

  # Compute missing connectors in on-prem
  IFS=' ' read -r -a missing_connectors_ids <<<"$(subtract_array_from_array on_prem_connectors_ids config_connectors_ids)"

  if [[ -n "${missing_connectors_ids[*]}" ]]; then
    print "Connector ids missing in toolkit"
    printf "%s\n" "${missing_connectors_ids[@]}"
  fi
}

function validate_fixed_properties() {
  local files_to_grep=()
  local error_messages=()
  local fixed_property
  local grep_result
  local properties_file
  local actual_property
  local fixed_property_value
  local expected_property

  files_to_grep=("${COMMON_CLASSES_DIR}/ApolloServerSettingsMandatory.properties")
  # If analyze-settings.properties does not exist also validate properties in DiscoServerSettingsCommon
  if [[ ! -f "${COMMON_CLASSES_DIR}/analyze-settings.properties" ]]; then
    files_to_grep+=("${OPAL_SERVICES_CLASSES_DIR}/DiscoServerSettingsCommon.properties")
  fi

  # Ensure properties are set to the expected fixed values
  for fixed_property in "${!FIXED_PROPERTIES[@]}"; do
    # Do not validate TypeMappingResource property
    if [[ "${fixed_property}" != "TypeMappingResource" ]]; then
      grep_result=$(grep "^${fixed_property}" "${files_to_grep[@]}")
      properties_file="$(echo "${grep_result}" | cut -d':' -f1)"
      actual_property="$(echo "${grep_result}" | cut -d':' -f2)"
      file_name=$(basename "${properties_file}")
      fixed_property_value=${FIXED_PROPERTIES[${fixed_property}]}
      expected_property="${fixed_property}=${fixed_property_value}"

      if [[ "${actual_property}" != "${expected_property}" ]]; then
        error_messages+=("The \"${actual_property}\" setting must be set to \"${fixed_property_value}\" in the ${file_name} file.")
      fi
    fi
  done

  if [[ "${#error_messages[@]}" -gt 0 ]]; then
    print_error_and_exit "${error_messages[@]}"
  fi
}

function append_error_message_if_file_not_exist() {
  local file="${1}"
  local error_message="The ${file} file does not exist. Ensure that it is in the configuration directory and has the correct name."
  if [[ ! -f "${file}" ]]; then
    error_messages+=("${error_message}")
  fi
}

function validate_fixed_files() {
  local error_messages=()

  # Ensure the configuration contains the default files
  for file in "${REQUIRED_COMMON_FIXED_FILE_NAMES[@]}"; do
    append_error_message_if_file_not_exist "$file"
  done
  allowed_files=("${REQUIRED_COMMON_FIXED_FILE_NAMES[@]}")

  # Check presence of analyze-settings.properties and if exists ensure the files exists
  if [[ -f "${COMMON_CLASSES_DIR}/analyze-settings.properties" ]]; then
    for file in "${REQUIRED_FRAGMENTS_FOR_ANALYZE_SETTINGS_FILE_NAMES[@]}"; do
      append_error_message_if_file_not_exist "$file"
    done
    allowed_files+=("${REQUIRED_FRAGMENTS_FOR_ANALYZE_SETTINGS_FILE_NAMES[@]}")
  fi

  # Check deployment pattern and ensure relevant files exist
  if [[ "${DEPLOYMENT_PATTERN}" == *"store"* ]]; then
    for file in "${REQUIRED_FRAGMENTS_FOR_ISTORE_DEPLOYMENT_FILE_NAMES[@]}"; do
      append_error_message_if_file_not_exist "$file"
    done
    allowed_files+=("${REQUIRED_FRAGMENTS_FOR_ISTORE_DEPLOYMENT_FILE_NAMES[@]}")
  else
    for file in "${REQUIRED_FRAGMENTS_FOR_I2C_DEPLOYMENT_FILE_NAMES[@]}"; do
      append_error_message_if_file_not_exist "$file"
    done
    allowed_files+=("${REQUIRED_FRAGMENTS_FOR_I2C_DEPLOYMENT_FILE_NAMES[@]}")
  fi

  if [[ "${#error_messages[@]}" -gt 0 ]]; then
    print_error_and_exit "${error_messages[@]}"
  fi
}

function warn_if_extra_files() {
  if [[ "${TASK}" == "import" ]]; then
    # Ensure there is no other properties file that aren't required
    files_to_validate=("$(find "${ON_PREM_CONFIG_DIR}/"* -type f \( -path "*/fragments/common/WEB-INF/classes/*" \
      -o -path "*/fragments/opal-services/WEB-INF/classes/*" \
      -o -path "*/fragments/opal-services-is/WEB-INF/classes/*" \
      -o -path "*/live/*" \))")

    IFS=' ' read -r -a extra_files <<<"$(subtract_array_from_array allowed_files files_to_validate)"
    IFS=' ' read -r -a extra_files <<<"$(subtract_array_from_array IGNORED_FIXED_FILE_NAMES extra_files)"

    if [[ "${#extra_files[@]}" -gt 0 ]]; then
      echo "The following files will not be imported into the config development environment configuration:"
      printf "%s\n" "${extra_files[@]}"

      wait_for_user_reply "Are you sure you want to continue?"
    fi
  fi
}

function validate_fixed_names() {
  local files_to_validate
  local extra_files=()
  local allowed_files

  print "Validating configuration: ${ON_PREM_CONFIG_DIR}"
  validate_fixed_properties
  validate_fixed_files
  warn_if_extra_files
}

function create_config() {
  local example_configuration
  local example_configuration_path
  local toolkit_config_mod_dir

  print "Running the create task"

  if [[ -d "${ON_PREM_CONFIG_DIR}" ]]; then
    wait_for_user_reply "To create a new configuration, the previous configuration directory must be deleted. Are you sure you want to delete your current i2 Analyze deployment toolkit configuration?"
    print "Deleting existing ${ON_PREM_CONFIG_DIR}"
    delete_folder_if_exists_and_create "${ON_PREM_CONFIG_DIR}"
  else
    create_folder "${ON_PREM_CONFIG_DIR}"
  fi

  case "${DEPLOYMENT_PATTERN}" in
  "i2c_istore")
    example_configuration="information-store-daod-opal"
    ;;
  "i2c")
    example_configuration="daod-opal"
    ;;
  "cstore")
    example_configuration="chart-storage"
    ;;
  "i2c_cstore")
    example_configuration="chart-storage-daod"
    ;;
  "istore")
    example_configuration="information-store-opal"
    ;;
  esac

  print "Copying example ${example_configuration} configuration to ${ON_PREM_TOOLKIT_DIR}"
  example_configuration_path="${EXAMPLES_CONFIGS_DIR}/${example_configuration}/configuration"
  cp -pr "${example_configuration_path}/"* "${ON_PREM_CONFIG_DIR}"

  print "Copying config development environment configuration mods to ${COMMON_CLASSES_DIR}"
  toolkit_config_mod_dir="${ANALYZE_CONTAINERS_ROOT_DIR}/templates/toolkit-config-mod"
  cp -p "${toolkit_config_mod_dir}/analyze-connect.properties" \
    "${toolkit_config_mod_dir}/analyze-settings.properties" \
    "${toolkit_config_mod_dir}/ApolloServerSettingsConfigurationSet.properties" \
    "${toolkit_config_mod_dir}/ApolloServerSettingsMandatory.properties" \
    "${COMMON_CLASSES_DIR}"

  print_success "configuration created"
}

function rename_config_files() {
  local actual_property
  local actual_filename
  local expected_filename

  for fixed_property in "${!FIXED_PROPERTIES[@]}"; do
    actual_property=$(grep -h "^${fixed_property}" "${COMMON_CLASSES_DIR}/ApolloServerSettingsMandatory.properties" "${OPAL_SERVICES_CLASSES_DIR}/DiscoServerSettingsCommon.properties" || true)
    actual_filename="$(echo "${actual_property}" | cut -d'=' -f2)"
    expected_filename="${FIXED_PROPERTIES[${fixed_property}]}"

    if [[ -n "${actual_filename}" ]]; then
      if [[ "${actual_filename}" != "${expected_filename}" ]]; then
        if [[ -n "${actual_filename}" ]]; then
          echo "${actual_filename} > ${expected_filename}"
        fi
        find "${FRAGMENTS_DIR}/"* -type f -name "${actual_filename}" -execdir mv {} "${expected_filename}" \;
      fi
    else
      unset_properties+=("${fixed_property}=${expected_filename}")
    fi
  done
}

function add_template_config_files() {
  local property_key
  local property_value
  local toolkit_config_mod_dir
  local fragments_classes_dir

  print_info "Add templates for unset settings"
  for unset_property in "${unset_properties[@]}"; do
    property_key="$(echo "${unset_property}" | cut -d'=' -f1)"
    property_value="$(echo "${unset_property}" | cut -d'=' -f2)"

    if [[ "${property_key}" == "SchemaResource" ]] || [[ "${property_key}" == "ChartingSchemesResource" ]] ||
      [[ "${property_key}" == "DynamicSecuritySchemaResource" ]] || [[ "${property_key}" == "TypeMappingResource" ]]; then
      fragments_classes_dir="${COMMON_CLASSES_DIR}"
    else
      fragments_classes_dir="${OPAL_SERVICES_CLASSES_DIR}"
    fi

    # If the settings file does not exist then copy a template file
    if [[ ! -f "${fragments_classes_dir}/${property_value}" ]]; then
      echo "Copying template ${property_value} to ${fragments_classes_dir}"
      cp -p "${LOCAL_USER_CONFIG_DIR}/${property_value}" "${fragments_classes_dir}"
    fi
  done

  print_info "Add templates for other files"
  other_files=("${REQUIRED_COMMON_FIXED_FILE_NAMES[@]}")
  if [[ "${DEPLOYMENT_PATTERN}" == *"store"* ]]; then
    other_files+=("${REQUIRED_FRAGMENTS_FOR_ISTORE_DEPLOYMENT_FILE_NAMES[@]}")
  else
    other_files+=("${REQUIRED_FRAGMENTS_FOR_I2C_DEPLOYMENT_FILE_NAMES[@]}")
  fi
  for file in "${other_files[@]}"; do
    if [[ ! -f "${file}" ]]; then
      filename="$(basename "${file}")"
      # Files can be in any directory. Copy it from template in the expected dir
      path="$(dirname "${file}")"
      echo "Copying template ${filename} to ${path}"
      cp -p "${LOCAL_USER_CONFIG_DIR}/${filename}" "${path}"
    fi
  done
}

function update_config_properties() {
  local grep_result
  local actual_property
  local expected_property
  local properties_file

  files_to_grep=("${COMMON_CLASSES_DIR}/ApolloServerSettingsMandatory.properties")
  # If analyze-settings.properties does not exist also check properties in DiscoServerSettingsCommon
  if [[ ! -f "${COMMON_CLASSES_DIR}/analyze-settings.properties" ]]; then
    files_to_grep+=("${OPAL_SERVICES_CLASSES_DIR}/DiscoServerSettingsCommon.properties")
  fi

  for fixed_property in "${!FIXED_PROPERTIES[@]}"; do
    # Do not update TypeMappingResource property
    if [[ "${fixed_property}" != "TypeMappingResource" ]]; then
      grep_result=$(grep "^${fixed_property}" "${files_to_grep[@]}")
      properties_file="$(echo "${grep_result}" | cut -d':' -f1)"
      actual_property="$(echo "${grep_result}" | cut -d':' -f2)"
      expected_property="${fixed_property}=${FIXED_PROPERTIES[${fixed_property}]}"

      if [[ "${actual_property}" != "${expected_property}" ]]; then
        echo "Updating ${expected_property}"
        sed -i "s/^${actual_property}/${expected_property}/" "${properties_file}"
      fi
    fi
  done
}

function prepare_config_files() {
  local unset_properties

  print "Running the prepare task"

  print "Renaming the schema and configuration files"
  rename_config_files

  print "Adding template files"
  add_template_config_files

  print "Updating the schema and configuration settings"
  update_config_properties

  print_success "configuration updated"
}

function import_dsid_properties_file() {
  local dsid_properties_directory_path="${LOCAL_USER_CONFIG_DIR}/environment/dsid"
  local dsid_properties_file_path="${dsid_properties_directory_path}/dsid.properties"
  local on_prem_dsid_properties_file_path
  local topology_id

  topology_id="$(get_topology_id)"
  on_prem_dsid_properties_file_path="${ON_PREM_CONFIG_DIR}/environment/dsid/dsid.${topology_id}.properties"

  if [[ -f "${on_prem_dsid_properties_file_path}" ]]; then
    create_folder "${dsid_properties_directory_path}"
    cp -p "${on_prem_dsid_properties_file_path}" "${dsid_properties_file_path}"
  fi
}

function import_plugins() {
  local plugin_references_file="${LOCAL_USER_CONFIG_DIR}"/plugin-references.json
  local temp_file="${LOCAL_USER_CONFIG_DIR}/temp.json"
  local on_prem_plugins=()
  local config_dev_plugins=()
  local plugins_to_import=()

  # Build on-prem plugin array
  for plugin_dir in "${OPAL_SERVICES_PLUGINS_DIR}"/*; do
    [[ ! -d "${plugin_dir}" ]] && continue
    plugin_name=$(basename "${plugin_dir}")
    on_prem_plugins+=("${plugin_name}")
  done

  # Build config-dev plugin array
  for plugin_dir in "${PLUGINS_DIR}"/*; do
    [[ ! -d "${plugin_dir}" ]] && continue
    plugin_name=$(basename "${plugin_dir}")
    config_dev_plugins+=("${plugin_name}")
  done

  IFS=' ' read -r -a plugins_to_import <<<"$(subtract_array_from_array config_dev_plugins on_prem_plugins)"
  if [[ "${#plugins_to_import[@]}" -gt 0 ]]; then
    IFS=' ' read -r -a plugins_to_exclude <<<"$(subtract_array_from_array plugins_to_import config_dev_plugins)"
  else
    plugins_to_exclude=("${on_prem_plugins[@]}")
  fi

  print "Importing Plugins"
  if [[ "${#plugins_to_import[@]}" -gt 0 ]]; then
    echo "The following plugins were found in the toolkit configuration and will be imported:"
    printf "%s\n" "${plugins_to_import[@]}"
    for plugin in "${plugins_to_import[@]}"; do
      cp -pr "${OPAL_SERVICES_PLUGINS_DIR}/"* "${PLUGINS_DIR}"
    done
  fi
  if [[ -n "${plugins_to_exclude[*]}" ]]; then
    echo "The following plugins already exist in i2a-plugins and were not imported:"
    printf "%s\n" "${plugins_to_exclude[@]}"
  fi

  print "Updating plugin-references.json"
  for plugin in "${plugins_to_import[@]}"; do
    jq -r \
      --arg plugin "${plugin}" \
      '.plugins += [{name: $plugin}]' \
      <"${plugin_references_file}" >"${temp_file}"
    mv "${temp_file}" "${plugin_references_file}"
  done
}

function import_config() {
  print "Running import task"

  validate_fixed_names

  print "Updating configuration: ${LOCAL_USER_CONFIG_DIR}"
  # Copy fragments/common, fragments/opal-services and live configuration files
  cp -p "${REQUIRED_COMMON_FIXED_FILE_NAMES[@]}" "${LOCAL_USER_CONFIG_DIR}"

  # Copy default config-dev files
  cp -pr "${LOCAL_CONFIG_DEV_DIR}/configuration/i2-tools" \
    "${LOCAL_CONFIG_DEV_DIR}/configuration/ingestion" \
    "${LOCAL_CONFIG_DEV_DIR}/configuration/connector-references.json" \
    "${LOCAL_CONFIG_DEV_DIR}/configuration/extension-references.json" \
    "${LOCAL_CONFIG_DEV_DIR}/configuration/log4j2.xml" \
    "${LOCAL_USER_CONFIG_DIR}"

  # Copy solr configuration files
  cp -pr "${ON_PREM_CONFIG_DIR}/solr"/*.* "${LOCAL_USER_CONFIG_DIR}/solr"

  # If the deployment toolkit analyze settings file exists then copy
  if [[ -f "${COMMON_CLASSES_DIR}/analyze-settings.properties" ]]; then
    cp -p "${COMMON_CLASSES_DIR}/analyze-settings.properties" "${LOCAL_USER_CONFIG_DIR}"
  fi

  # Check deployment pattern and copy relevant files
  if [[ "${DEPLOYMENT_PATTERN}" == *"store"* ]]; then
    cp -p "${REQUIRED_FRAGMENTS_FOR_ISTORE_DEPLOYMENT_FILE_NAMES[@]}" "${LOCAL_USER_CONFIG_DIR}"
  else
    cp -p "${REQUIRED_FRAGMENTS_FOR_I2C_DEPLOYMENT_FILE_NAMES[@]}" "${LOCAL_USER_CONFIG_DIR}"
  fi

  import_dsid_properties_file

  import_plugins

  # Copy liberty configuration files
  cp -pr "${ON_PREM_CONFIG_DIR}/liberty"/*.* "${LOCAL_USER_CONFIG_DIR}"

  if [[ -f "${FRAGMENTS_DIR}/common/privacyagreement.html" ]]; then
    cp -p "${FRAGMENTS_DIR}/common/privacyagreement.html" "${LOCAL_USER_CONFIG_DIR}/privacyagreement.html"
  fi

  print_success "configuration updated"

  generate_artifacts

  validate_and_list_connectors

  echo "Generated config is in: ${LOCAL_USER_CONFIG_DIR}"
}

function export_config() {
  local apollo_server_settings_file_path
  print "Running export task"

  # Creating transient .configuration and .configuration-generated directories
  generate_artifacts
  create_mounted_config_structure

  print "Generating configuration for the export"
  delete_folder_if_exists "${LOCAL_CONFIG_DIR}/environment/common"
  delete_folder_if_exists "${LOCAL_CONFIG_DIR}/i2-tools"
  delete_folder_if_exists "${LOCAL_CONFIG_DIR}/ingestion"
  delete_folder_if_exists "${LOCAL_CONFIG_DIR}/solr/generated_config"
  delete_folder_if_exists "${LOCAL_CONFIG_DIR}/prometheus"
  delete_folder_if_exists "${LOCAL_CONFIG_DIR}/grafana"
  rm "${LOCAL_CONFIG_DIR}/fragments/common/WEB-INF/classes/log4j2.xml"
  rm "${LOCAL_CONFIG_DIR}/fragments/opal-services/WEB-INF/classes/connectors-template.json"
  rm "${LOCAL_CONFIG_DIR}/fragments/opal-services/WEB-INF/classes/DiscoSolrConfiguration.properties"
  rm "${LOCAL_CONFIG_DIR}/liberty/server.extensions.dev.xml"
  rm "${LOCAL_CONFIG_DIR}/liberty/user.registry.xml"

  # If on prem analyze settings file does not exist then exclude files from copy
  # If on prem analyze settings file exists:
  #   Ensure analyze-settings.properties is included
  #   Add required setting to ApolloServerSettingsMandatory

  if [[ ! -f "${COMMON_CLASSES_DIR}/analyze-settings.properties" ]]; then
    rm "${LOCAL_CONFIG_DIR}/fragments/common/WEB-INF/classes/analyze-settings.properties"
    rm "${LOCAL_CONFIG_DIR}/fragments/common/WEB-INF/classes/analyze-connect.properties"
    rm "${LOCAL_CONFIG_DIR}/fragments/common/WEB-INF/classes/ApolloServerSettingsConfigurationSet.properties"
    rm "${LOCAL_CONFIG_DIR}/fragments/common/WEB-INF/classes/ApolloServerSettingsMandatory.properties"
  else
    # Exclude files from copy
    rm "${LOCAL_CONFIG_DIR}/fragments/common/WEB-INF/classes/analyze-connect.properties"
    rm "${LOCAL_CONFIG_DIR}/fragments/common/WEB-INF/classes/ApolloServerSettingsConfigurationSet.properties"
  fi

  # Check deployment pattern and exclude certain files from copy
  if [[ "${DEPLOYMENT_PATTERN}" == *"store"* ]]; then
    create_folder "${LOCAL_CONFIG_DIR}/environment"
    mv "${LOCAL_CONFIG_DIR}/live/system-match-rules.xml" "${LOCAL_CONFIG_DIR}/environment"
  fi

  print "Updating configuration: ${ON_PREM_CONFIG_DIR}"
  cp -r "${LOCAL_CONFIG_DIR}/." "${ON_PREM_CONFIG_DIR}"
  validate_fixed_names
  print_success "configuration updated"

  validate_and_list_connectors
}

function run_task() {
  if [[ "${TASK}" == "create" ]]; then
    create_config
  elif [[ "${TASK}" == "prepare" ]]; then
    prepare_config_files
  elif [[ "${TASK}" == "import" ]]; then
    import_config
  elif [[ "${TASK}" == "export" ]]; then
    export_config
  fi
}

function main() {
  OPTIONS_FOR="manageToolkitConfig"
  parse_arguments "$@"
  validate_arguments
  set_defaults
  run_top_level_checks
  source_common_variables_and_scripts
  warn_root_dir_not_in_path
  run_low_level_checks
  run_task
}

main "$@"
