#!/usr/bin/env bash
# i2, i2 Group, the i2 Group logo, and i2group.com are trademarks of N.Harris Computer Corporation.
# © N.Harris Computer Corporation (2022-2023)
#
# SPDX short identifier: MIT

set -e

source "/opt/utils/common_functions.sh"

function print_usage() {
  echo "Usage:"
  echo "    validate-i2-connect-versions" 1>&2
  echo "    validate-i2-connect-versions -h" 1>&2
}

function usage() {
  print_usage
  exit 1
}

function help() {
  print_usage
  echo "Options:"
  echo "    -h Display the help." 1>&2
  echo "Required Environment Variables:" 1>&2
  echo "    CONFIG_I2CONNECT_SERVER_VERSION" 1>&2
  echo "    DECLARED_I2CONNECT_SERVER_VERSION" 1>&2
  echo "    CONFIG_CONNECTOR_VERSION" 1>&2
  echo "    DECLARED_CONNECTOR_VERSION" 1>&2
  exit 1
}

function validate_env_vars_are_set() {
  check_variable_is_set "${CONFIG_I2CONNECT_SERVER_VERSION}" "The expected i2 Connect Server version could NOT be determined from i2connect-server-version.json"
  check_variable_is_set "${DECLARED_I2CONNECT_SERVER_VERSION}" "The declared i2 Connect Server version could NOT be determined from package.json"
  check_variable_is_set "${CONFIG_CONNECTOR_VERSION}" "The expected connector version could NOT be determined from connector-version.json"
  check_variable_is_set "${DECLARED_CONNECTOR_VERSION}" "The declared connector version could NOT be determined from package.json"
}

#######################################
# Gets the latest compatible version
# of the i2Connect Server npm package
# compatible with the given semantic
# version.
# Arguments:
#   The desired semantic version
#######################################
function get_i2_connect_server_version() {
  local semantic_version="${1}"
  local npm_output
  local version

  npm_output=$(npm view "@i2analyze/i2connect@${semantic_version}" version | sort | tail -n1)
  if [[ -z "${npm_output}" ]]; then
    print_error_and_exit "An i2 Connect Server version compatible with ${semantic_version} does NOT exist"
  fi

  if [[ $npm_output = *" "* ]]; then
    version="${npm_output##* }"
    version="${version//\'/}"
  else
    version="${npm_output}"
  fi
  echo "${version}"
}

function validate_node_sdk_version() {
  local latest_config_i2connect_server_version
  local latest_declared_i2connect_server_version

  print "Validating i2 Connect Server version"
  echo "Expected i2 Connect Server version: ${CONFIG_I2CONNECT_SERVER_VERSION}"
  echo "Declared i2 Connect Server version: ${DECLARED_I2CONNECT_SERVER_VERSION}"
  latest_config_i2connect_server_version="$(get_i2_connect_server_version "${CONFIG_I2CONNECT_SERVER_VERSION}")"
  latest_declared_i2connect_server_version="$(get_i2_connect_server_version "${DECLARED_I2CONNECT_SERVER_VERSION}")"

  if [[ "${latest_config_i2connect_server_version}" != "${latest_declared_i2connect_server_version}" ]]; then
    wait_for_user_reply "The expected and declared i2 Connect Server versions (from i2connect-server-version.json and package.json) are not the compatible. Would you like to continue?"
  fi
}

function validate_connector_version() {
  print "Validating connector version"
  echo "Expected connector version: ${CONFIG_CONNECTOR_VERSION}"
  echo "Declared connector version: ${DECLARED_CONNECTOR_VERSION}"
  if [[ "${DECLARED_CONNECTOR_VERSION}" != "${CONFIG_CONNECTOR_VERSION}"* ]]; then
    wait_for_user_reply "The expected and declared connector versions (from connector-version.json and package.json) are not the compatible. Would you like to continue?"
  fi
}

while getopts ":h" flag; do
  case "${flag}" in
  h)
    help
    ;;
  \?)
    usage
    ;;
  :)
    echo "Invalid option: ${OPTARG} requires an argument"
    ;;
  esac
done

print "Validating versions for the connector: ${CONNECTOR_NAME}"
validate_env_vars_are_set
validate_node_sdk_version
validate_connector_version
